kube-burner/kube-burner-ocp

cmd/ocp.go
Using logrus in ocp.go
- Closes #
=> Use configFile argument

.github/workflows/builders.yml, .github/workflows/docs.yml, .github/workflows/gorelease.yml, .github/workflows/test-ocp.yml
Node 20 based actions are deprecated
=> Node 20 GHA

cmd/config/web-burner-init/pod_serving.yml
Quick fix for https://github.com/kube-burner/kube-burner/issues/600
=> Fix for kube-burner/issues/600

cmd/config/metrics-report.yml
These metrics are incorrect, they must be instant
=> API metrics should be instant

Makefile
Reverting this change as someone can simply clone the latest KB and replace it using the below command in their local
```
go mod edit  -replace  github.com/kube-burner/kube-burner=/home/rsevilla/labs/kube-burner
```
This is very specific to having knowledge in GO and contributors using KB as dependency are expected to have knowledge about fixing dependency issues.
=> Revert replace-import as it not required

.github/workflows/docs.yml
Keeping git config username and email different from kube-burner docs workflow.
**Related Issue:** Having same git config on both the repos might tamper the docs deploy workflows. So keep them different from each other.
This change will be originally tested when cut a release. But in dev environment, tested and verified by deleting older tags and keep the below two doc links updated.
* https://kube-burner.github.io/kube-burner/latest/
* https://kube-burner.github.io/kube-burner-ocp/latest/
=> Changing git config for docs

cmd/config/web-burner-init/permissionsServiceAccount.yml
Small fix for https://github.com/kube-burner/kube-burner-ocp/issues/42
- Related Issue https://github.com/kube-burner/kube-burner-ocp/issues/42
- Closes https://github.com/kube-burner/kube-burner-ocp/issues/42
=> Fixes web-burner with newer kube-burner versions

cmd/config/web-burner-cluster-density/web-burner-cluster-density.yml, cmd/config/web-burner-init/web-burner-init.yml, cmd/config/web-burner-node-density/web-burner-node-density.yml
- Parametrize the QPS variable for the web-burner-init workload
- Speed up the test
=> Parametrize QPS for web-burner-init workload

cmd/config/web-burner-init/web-burner-init.yml
Disable PodSecurity warnings in web-burner workload.
=> Disable PodSecurity warnings in web-burner workload

cmd/ocp.go
Enabling health check by default
- Related Issue #79
- Closes #
=> Enable health check by default

README.md, cmd/config/metrics-aggregated.yml, cmd/config/metrics-egressip.yml, cmd/config/metrics-report.yml, cmd/config/metrics.yml, cmd/ocp.go, common.go, egressip.go
Enabling `captureStart` for the required metrics, please @afcollins , verify I'm not missing any.
- Closes #
=> Adding captureStart to required metrics

cmd/ocp.go
Just added from kube-burner package, outputs log file.
- Closes #
=> outputs log file similar to kube-burner

.github/workflows/ci-tests.yml, .github/workflows/test-ocp.yml, test/test-ocp.bats
Removing dev ES instance and replacing it with prod ones
- Closes # https://issues.redhat.com/browse/PERFSCALE-3430
Can only be tested once this PR is merged.
=> Removing Dev ES instance reference

workers-scale.go
Making workers-scale to capture custom metrics.
=> Making workers-scale to accept custom metrics

cmd/ocp.go
Logs similar to kube-burner
- Closes #
=> Logs similar to kube-burner.

pkg/workerscale/utils.go
Removing redudant std configuration to fix cmd bugs in PROW.
=> Remove redundant StdOut and StdError for cmd

.github/workflows/linters.yml, go.mod, go.sum, index.go, pkg/workerscale/autoscaler.go, pkg/workerscale/base.go, pkg/workerscale/metrics.go, pkg/workerscale/rosa.go, pkg/workerscale/types.go, types.go, workers-scale.go
* Adds imageID in the jobSummary
* Updates the latest go-commons code that helps us detect ES indexing issues in early stages.
* Fix workers count calculation for different scenarios. Also indexing issues due to existing mapping conflicts in ES.
=> Enhancements for worker-scale metrics

README.md, cmd/config/rds-core/bgpadvertisement.yml, cmd/config/rds-core/bgppeer.yml, cmd/config/rds-core/configmap.yml, cmd/config/rds-core/deployment-client.yml, cmd/config/rds-core/deployment-dpdk.yml, cmd/config/rds-core/deployment-server.yml, cmd/config/rds-core/ipaddresspool.yml, cmd/config/rds-core/np-allow-from-clients.yml, cmd/config/rds-core/np-allow-from-ingress.yml, cmd/config/rds-core/np-deny-all.yml, cmd/config/rds-core/rds-core.yml, cmd/config/rds-core/route.yml, cmd/config/rds-core/secret.yml, cmd/config/rds-core/service-lb.yml, cmd/config/rds-core/service.yml, cmd/config/rds-core/sriov-network.yml, cmd/ocp.go, rds-core.go
Add a core RDS workload. CI tests will be onboarded on a separate PR.
```
time="2024-10-24 15:45:59" level=info msg="❤️ Checking for Cluster Health" file="cluster_health.go:45"
time="2024-10-24 15:45:59" level=info msg="Cluster is Healthy" file="cluster_health.go:53"
time="2024-10-24 15:45:59" level=info msg="🔥 Starting kube-burner (rds@c5937be4e3101d1df4fbe88d976047f404507fac) with UUID 5a41f860-46fd-440b-b8d3-35a447198a72" file="job.go:110"
time="2024-10-24 15:45:59" level=info msg="📈 Registered measurement: podLatency" file="factory.go:90"
time="2024-10-24 15:45:59" level=info msg="📈 Registered measurement: serviceLatency" file="factory.go:90"
time="2024-10-24 15:45:59" level=info msg="Job bgp-setup: 1 iterations with 1 IPAddressPool replicas" file="create.go:92"
..
time="2024-10-24 …
```
=> [PERFSCALE-3052] Add new core RDS workload

cmd/ocp.go
=> Disable health check on index subcmd

cmd/ocp.go
Disable file logging when --extract is set
- Closes #142
=> Disable file logging on extract

cmd/config/crd-scale/crd-scale.yml, test/test-ocp.bats
Add a test case for the crd-scale workload, and remove pvc-density, which is currently unused
- Closes #95
=> CRD test case

cmd/config/alerts.yml
Leverage the labels of this alert in a new one and filter it out it from the original alert expression.
=> Add explicit alert for ClusterOperatorDown

cmd/config/udn-density-pods/udn-density-pods.yml
=> preload images in the nodes for the udn workload

Makefile
- Optimization
Since the configuration files are embedded into the binary, make sure it is built when a configuration file changes
=> Makefile - add the configuration files to the binary sources

Makefile
- Optimization
Makefile - build binary when go.mod changes
=> Makefile - build binary when go.mod changes

.github/workflows/test-ocp.yml
- CI
Install virtctl since it is a requirement for the tests
=> CI - Install virtctl

cmd/config/egressip/egressip.yml, cmd/config/rds-core/rds-core.yml, cmd/config/udn-density-pods/udn-density-pods.yml, cmd/config/web-burner-cluster-density/web-burner-cluster-density.yml, cmd/config/web-burner-init/web-burner-init.yml, cmd/config/web-burner-node-density/web-burner-node-density.yml, pvc-density.go, test/test-ocp.bats
Maximizing CI Coverage.
More details in this [spreadsheet](https://docs.google.com/spreadsheets/d/1_Zig4Dh6x-RCYhLcWXvT6aF017zgQUfs-rM8OUTzQ_Q/edit?gid=144606043#gid=144606043)
Added CI tests for all the workloads except for the ones that require special hardware requirments.
Closes # https://issues.redhat.com/browse/PERFSCALE-3705
=> Maximizing CI Coverage

README.md, cmd/config/virt-clone/check.sh, cmd/config/virt-clone/templates/baseImageDataSource.yml, cmd/config/virt-clone/templates/baseImageDataVolume.yml, cmd/config/virt-clone/templates/baseImageDataVolumeSnapshot.yml, cmd/config/virt-clone/templates/secret_ssh_public.yml, cmd/config/virt-clone/templates/vm.yml, cmd/config/virt-clone/virt-clone.yml, cmd/ocp.go, common.go, test/test-ocp.bats, virt-clone.go
- New feature
The new test follows the VDI scenario in which VMs are created based on a master image from another VM
=> Add test for creating Virtual Machines from a master image

README.md, cmd/config/virt-capacity-benchmark/virt-capacity-benchmark.yml, common.go, test/ocp/custom-workload.yml, test/test-ocp.bats, virt-capacity-benchmark.go
- Optimization
- CI
Add command line parameters to tweak the test when running in the CI
=> Adjust virt-capacity-benchmark test to pass the CI

cmd/config/metrics.yml
- Refactor
- New feature
- Bug fix
- Optimization
- CI
Adding major page faults to our kube-burner-ocp collection
- Closes #
=> Add major page faults to collection

README.md, cmd/config/virt-density/virt-density.yml, cmd/config/virt-density/vm.yml, cmd/config/virt-udn-density/service.yml, cmd/config/virt-udn-density/udn_l2.yml, cmd/config/virt-udn-density/udn_l3.yml, cmd/config/virt-udn-density/virt-udn-density.yml, cmd/config/virt-udn-density/vm-client.yml, cmd/config/virt-udn-density/vm-server.yml, cmd/ocp.go, common.go, test/test-ocp.bats, virt-density-udn.go, virt-density.go
- New feature
Deployed a UDN in any namespace iterations and 2 VMs (client/server) using their UDN interface to communicate.
- Closes #
=> UDN Virt density scenario

.github/workflows/test-ocp.yml
- Optimization
- CI
Add TEST_BINARY to environment in preparation for adding support for running the tests locally
Also remove unused variables
=> GitHub Workflow - Add TEST_BINARY to CI environment

.github/workflows/test-ocp.yml, Makefile, test/helpers.bash, test/test-ocp.bats
- CI
Compute TEST_BINARY in the Makefile if not set
Pass KUBE_BURNER_OCP to bats
Allow filtering
=> Allow running CI tests locally

README.md, cmd/config/virt-clone/virt-clone.yml, cmd/config/virt-ephemeral-restart/check.sh, cmd/config/virt-ephemeral-restart/templates/baseImageDataSource.yml, cmd/config/virt-ephemeral-restart/templates/baseImageDataVolume.yml, cmd/config/virt-ephemeral-restart/templates/baseImageDataVolumeSnapshot.yml, cmd/config/virt-ephemeral-restart/templates/secret_ssh_public.yml, cmd/config/virt-ephemeral-restart/templates/vm.yml, cmd/config/virt-ephemeral-restart/virt-ephemeral-restart.yml, cmd/ocp.go, common.go, test/test-ocp.bats, virt-capacity-benchmark.go, virt-ephemeral-restart.go
- New feature
- CI
Add new test workload for restarting ephemeral VMs
=> Add test for ephemeral VMs restart performance

.codespellrc, .pre-commit-config.yaml, README.md, pvc-density.go, routeadvertisement-latency.go
- CI
Add codespell to the pre-commit-hooks
=> Add codespell to pre-commit step

cmd/config/metrics-report-stackrox.yml, cmd/config/metrics-report.yml
- Refactor
- New feature
- Bug fix
- Optimization
- CI
It's possible to append multiple profiles to the same run, so let's move these metrics for better organization cc @jtaleric 
- Closes #
=> Move Stackrox metrics to a separate profile

cmd/ocp.go
- New feature
Enabled by default
- Closes #239
=> Flag to enable/disable file logging

README.md, cluster_health.go, cmd/config/olm/clustercatalog.yml, cmd/config/olm/olm.yml, cmd/ocp.go, olmv1.go, test/test-ocp.bats
- New feature
- CI
OLMv1 testing touches 1 key area:
- ClusterCatalog
=> OLMv1 workload

cmd/config/rds-core/bgpadvertisement.yml
- Bug fix
Typo fix
- Closes https://github.com/kube-burner/kube-burner-ocp/issues/247
=> Fix RDS core typo

common.go, egressip.go, index.go, pkg/measurements/routeadvertisement-latency_linux.go, virt-capacity-benchmark.go, virt-clone.go
- Refactor
- New feature
- Bug fix
- Optimization
- CI
```golang
$ go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix ./...
```
- Closes #
=> Modernize golang code

README.md, cmd/config/virt-migration/check.sh, cmd/config/virt-migration/templates/remove_affinity_patch.yml, cmd/config/virt-migration/templates/secret_ssh_public.yml, cmd/config/virt-migration/templates/vm.yml, cmd/config/virt-migration/virt-migration.yml, cmd/ocp.go, common.go, virt-migration.go
- New feature
- CI
Add a new test sequence for virtual machine migration
=> New Test - Virt Migration

virt-migration.go
- Bug fix
Fix call to RunWithAdditionalVars
=> Virt Migration - fix call to run

cmd/config/udn-density-pods/udn-density-pods.yml
- Bug fix
declared as a bool https://github.com/kube-burner/kube-burner-ocp/blob/b43c6416dc32a3fd5366a6c0011eb98fc013329a/udn-density-pods.go#L72
=> check for bool instead of string for SIMPLE in udn test

.github/workflows/test-ocp.yml
- CI
Apply the logic implemented in https://github.com/kube-burner/kube-burner/pull/936 to this CI as well
=> CI - get KubeVirt version using GH CLI
