cmd/config/metrics-aggregated.yml

Some prow jobs are failing due to timeouts related to long Prometheus indexing tasks. The two worse offenders are `containerCPU-AggregatedWorkers` and `containerMemory-AggregatedWorkers`:
```
time="2024-01-15 04:35:37" level=info msg="Indexing metric containerCPU-AggregatedWorkers" file="prometheus.go:101"
time="2024-01-15 05:05:49" level=info msg="Indexing finished in 30m12.317s: created=464966 updated=30144" file="prometheus.go:107"
```
- Related Issue: https://redhat-internal.slack.com/archives/C020CKMP6CT/p1705306161906339
- Original PR and corresponding discussion: https://github.com/kube-burner/kube-burner/pull/579

Query fix to avoid prometheus timeouts

---

cmd/config/cluster-density-v2/np-allow-from-clients.yml
cmd/config/cluster-density-v2/np-allow-from-ingress.yml

Network policies in cluster-density-v2 weren't 100% correct and were allowing traffic to all ports to come in.
Before this change:
```
$ oc describe networkpolicy allow-from-clients                                                                                                                                   
Name:         allow-from-clients                                                                                                                                                                                                              
Namespace:    default                                                                                                                                                                                             
Created on:   2024-02-09 13:00:22 …
```

Fixing cluster-density network policies

---

cluster-density.go
cmd/config/cluster-density-v2/cluster-density-v2.yml
cmd/config/node-density-cni/node-density-cni.yml
node-density-cni.go
test/test-ocp.bats

Adding `service-latency` flag, by default false, to node-density-cni and cluster-density workloads

Service latency flag

---

cmd/ocp.go

Skipping PersistentPreRun() when using the version subcmd
- Closes #10

Skip PersistentPreRun on version subcmd

---

web-burner.go

Correcting a variable missmatch introduced by https://github.com/kube-burner/kube-burner-ocp/pull/22

Fix web-burner ICNI var

---

cmd/config/cluster-density-v2/np-allow-from-clients.yml

W/o this rule, the measurement fails in cdv2
- Closes #

Add missing kube-burner-service-latency namespace in networkpolicy

---

Makefile

Adding a make target to replace imports as follow up for this PR: https://github.com/kube-burner/kube-burner/pull/613/files

Adding make target to replace imports

---

cluster-density.go
cluster_health.go
custom-workload.go

Cluster health check shouldn't be executed in custom-workload and cluster-density by default. A user should opt-out this functionally with the flags.
- Closes #

Disable default cluster health check in BYOWL workloads

---

cmd/config/metrics-report.yml

For telco use cases _maximum_ is more relevant than _average_. Nowadays the reporting profile only includes maximum metrics for memory, but not for CPU and latency. This PR adds _maximum_ for the missing metrics.
- Related Issue https://github.com/kube-burner/kube-burner-ocp/issues/50
- Closes https://github.com/kube-burner/kube-burner-ocp/issues/50
If/when merged we should change the grafana **_kube-burner/Kube-burner report mode_** dashboard for **_Jose/Kube-burner report telco_**

Maximum metrics for CPU/latency in the report profile

---

cmd/config/cluster-density-v2/np-allow-from-ingress.yml

After / Before -
```
[root@e24-h01-000-r640 ~]# oc get namespace -l network.openshift.io/policy-group=ingress
NAME                     STATUS   AGE
openshift-host-network   Active   24h
openshift-ingress        Active   24h
[root@e24-h01-000-r640 ~]# oc get namespace -l kubernetes.io/metadata.name=openshift-ingress
NAME                STATUS   AGE
openshift-ingress   Active   24h
[root@e24-h01-000-r640 ~]#
```
- Closes #

Baremetal was broken due to incorrect np

---

index.go
test/test-ocp.bats

Support for multiple metric profiles in the index sub-command.
Tested in local with different scenarios
```
kube-burner-ocp index --uuid="${UUID}" --metrics-profile "metrics.yml,metrics.yml"
kube-burner-ocp index --uuid="${UUID}" --metrics-profile metrics.yml
kube-burner-ocp index --uuid="${UUID}" --metrics-profile "metrics.yml"
kube-burner-ocp index --uuid="${UUID}" --metrics-profile metrics.yml,metrics.yml
```

Adding support for multiple metric profiles

---

cmd/config/web-burner-init/pod_serving.yml

When we bumped FRR version from 8.0 to 8.5 as part of the multiarch effort FRR BFD **LocalAdress** field got populated to 0.0.0.0, breaking the readiness probe conditions:
```
sh-5.1# vtysh -c 'show bfd peers brief'
Session count: 2
SessionId  LocalAddress                             PeerAddress                             Status
=========  ============                             ===========                             ======
3980134474 192.168.219.1                            192.168.216.2                           up
1176606216 unknown                                  192.168.216.4                           down
sh-5.1# rpm -aq frr
frr-8.0-5.el9.x86_64
```
```
sh-5.1# vtysh -c 'show bfd peers brief'
Session count: 2
SessionId  LocalAddress                             PeerAddress …
```

[web-burner] Add explicit frr local-address

---

cmd/config/web-burner-cluster-density/web-burner-cluster-density.yml

When limitount is greater than 1:
```
time="2024-06-18 12:59:45" level=fatal msg="error decoding configuration file: yaml: unmarshal errors:\n  line 163: mapping key \"jobIterations\" already defined at line 162" file="helpers.go:85"
```
This PR fixes this.

jobIterations issue adjustment in web-burner-cluster-density

---

custom-workload.go

Collects all CLI arguments from other subcommands and adds them to custom workload, so they may be used in config templating, if desired.
Especially when using `kube-burner-ocp` in scripts, CLI arguments are more flexible than changing config files or maintaining separate config files.
- Closes #55

Add all cli argmuents to custom workload. Fixes #55

---

custom-workload.go

This flag is not used anymore, job name is used instead of benchmark name
- Closes #

Remove unused benchmark flag

---

cmd/config/crd-scale/example-crd.yml

Namespaced CRDs allow better to chunking into namespaces for a variety of purposes. When they are cluster scoped, their application can be less flexible.

Make crd-scale Namespaced scope

---

cmd/config/crd-scale/crd-scale.yml

Adding `waitOptions` to crd-scale workload, to wait for all crd to be in `Established` state before cleanup. 
Without wait 
```
time="2024-07-23 16:58:37" level=info msg="Verifying created objects" file="utils.go:85"
time="2024-07-23 16:58:38" level=info msg="customresourcedefinitions found: 20 Expected: 20" file="utils.go:118"
time="2024-07-23 16:58:38" level=info msg="Job crd-scale took 1s" file="job.go:197"
time="2024-07-23 16:58:38" level=info msg="Indexing metric jobSummary" file="metadata.go:58"
time="2024-07-23 16:58:38" level=info msg="Deleting non-namespace CustomResourceDefinition with selector kube-burner-job=crd-scale" file="namespaces.go:59"
```
With wait
```
time="2024-07-23 16:50:49" level=info msg="Waiting up to 4h0m0s for actions to be completed" file="create.go:178" …
```

Adding wait conditions to crd-scale

---

cmd/ocp.go

When using metrics-endpoint we shouldn't set any environment variables used for indexing
- Closes #

Don't set indexing vars when metrics-endpoint is set

---

cluster-density.go
cluster_health.go

Added image registry check for kube-burner-ocp, this can be used for bare-metal instances where image-registry co is not present by default.
- Related Issue #79
- Closes #

added image-registry check

---

README.md

kube-burner is throwing error when abolute path of the file is passed --metrics-endpoint option.
kube-burner is also failing to create prometheus client when https prefix is not added to preometheus endpoint

Docs update for metrics endpoint

---

custom-workload.go

These two flags should have a null default value, that is causing that the value of pods-per-node=50 takes precedence over the value configured in --iterations, as they are mutually exclusive, it's not possible to set iterations to a value different than pods-per-node.
w/o patch:
```yaml
rsevilla@wonderland ~/labs/kube-burner-ocp/test/ocp (main) $ cat ^C
rsevilla@wonderland ~/labs/kube-burner-ocp/test/ocp (main) $ cat  custom-workload.yml 
---
jobs:
- name: node-density
namespace: node-density
jobIterations: {{.JOB_ITERATIONS}}
qps: {{.QPS}}
burst: {{.BURST}}
namespacedIterations: false
podWait: false
waitWhenFinished: true
preLoadImages: true
preLoadPeriod: 10s
namespaceLabels:
security.openshift.io/scc.podSecurityLabelSync: false
pod-security.kubernetes.io/enforce: privileged …
```

pods-per-node and iterations shouln't have default values higher than 0

---

.golangci.yml
.pre-commit-config.yaml
cluster_health.go
egressip.go
index.go

The previous hook wasn't working as expected as it was relying on this configuration https://github.com/golangci/golangci-lint/blob/master/.pre-commit-hooks.yaml#L1-L8 `golangci-lint run --new-from-rev HEAD --fix`, the hook's command basically fixes linting errors when the current code is different from HEAD (so no action is taken when changes are committed), this is not what we actually need, we want to report and hang on linting errors caused by a PR.
Also fixing some pieces of code to meet linting.
- Closes #

Fix golangci-lint precommit hook

---

cmd/config/udn-density-l3-pods/udn-density-l3-pods.yml
udn-density-l3-pods.go

These flags and vars have no any effect and can be removed to avoid confussions
- Closes #

Remove useless flags

---

cluster-density.go
common.go
crd-scale.go
egressip.go
index.go
networkpolicy.go
node-density-cni.go
node-density-heavy.go
node-density.go
pvc-density.go
test/ocp/custom-metrics.yml
test/ocp/metrics-endpoints.yaml
test/ocp/metrics.yml
test/test-ocp.bats
udn-density-l3-pods.go
web-burner.go

Small implementation of the --metrics-profile flag
- Closes #110

Custom metric-profile list from flag

---

README.md
cluster-density.go
common.go
go.mod
go.sum
index.go
test/helpers.bash
workers-scale.go

Follow-up of https://github.com/kube-burner/kube-burner/pull/702
As agreed with the team (cc @mukrishn), let's add a small subset of metadata fields to all metrics (ocpVersion and ocpMajorVersion) generated by kube-burner.
- Closes #

Subset of metadata fields

---

crd-scale.go
custom-workload.go
egressip.go
networkpolicy.go
node-density-cni.go
node-density-heavy.go
node-density.go
pvc-density.go
udn-density-l3-pods.go
web-burner.go
workers-scale.go

os.exit() is removed from kube-burner helpers Run() method with the PR https://github.com/kube-burner/kube-burner/pull/704
kube-burner-ocp workloads now explicitly define PostRun and call os.exit().
This change helps workloads to do any cleanup as part of PostRun once kube-burner finishes execution.
Note: This patch depends on kube-burner PR
https://github.com/kube-burner/kube-burner/pull/704

add PostRun for workloads

---

cmd/config/cluster-density-ms/cluster-density-ms.yml
cmd/config/cluster-density-v2/cluster-density-v2.yml

The cluster-density deployments are created before the secrets and configmaps they depend on.
This can cause scheduling delays and in some cases cause errors in the apiserver.
- Closes #

Arrange deployments that depend on secrets and configmaps to be created after said resources

---

pkg/workerscale/autoscaler.go
pkg/workerscale/constants.go
pkg/workerscale/machines.go
workers-scale.go

Bug fix for autoscaler calculation in self-managed platforms. Fixes this failure: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/58074/rehearse-58074-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.16-nightly-x86-kube-burner-workers-autoscale-24nodes/1849037236960497664

Bug fix for autoscaler calculation in self-managed

---

.github/workflows/linters.yml
pkg/workerscale/metrics.go
pkg/workerscale/rosa.go
pkg/workerscale/types.go
workers-scale.go

Fixing all indexing related issues  in workers-scale workload.

Fixing indexing bugs for workers-scale

---

cmd/config/metrics-aggregated.yml
cmd/config/metrics-egressip.yml
cmd/config/metrics-report.yml
cmd/config/metrics.yml

Adding corresponding memory RSS queries for existing cgroup metrics.

Add cgroup RSS queries

---

cmd/config/metrics-aggregated.yml
cmd/config/metrics-egressip.yml
cmd/config/metrics.yml

This KPI is already tracked by alerts, there's no need to index it.
Here
https://github.com/kube-burner/kube-burner-ocp/blob/b2e40016e49ccbd9512862d2de556b5cb48ceb3b/cmd/config/alerts.yml#L11-L13
and here
https://github.com/kube-burner/kube-burner-ocp/blob/b2e40016e49ccbd9512862d2de556b5cb48ceb3b/cmd/config/alerts.yml#L58-L61

Remove etcd leader change metric

---

cmd/ocp.go
common.go
index.go

With this PR, the index subcmd will be able to use metrics profiles embedded in the `kube-burner-ocp` binary, ~~when the flag --embedded is passed~~
Using an embedded profile
```shell
$ kube-burner-ocp index --metrics-profile metrics.yml  --check-health=false
time="2024-11-07 17:02:32" level=info msg="📁 Creating local indexer: indexer-0" file="metrics.go:67"
time="2024-11-07 17:02:32" level=info msg="👽 Initializing prometheus client with URL: https://prometheus-k8s-openshift-monitoring.apps.kube-burner-ocp.perfscale.devcluster.openshift.com" file="prometheus.go:47"
time="2024-11-07 17:02:32" level=info msg="🔍 Endpoint: https://prometheus-k8s-openshift-monitoring.apps.kube-burner-ocp.perfscale.devcluster.openshift.com; profile: config/metrics.yml start: 2024-11-07T16:02:26+01:00 end: …
```

Use embedded metrics-profiles in index subcmd

---

cmd/config/whereabouts/ipam-fast.yml
cmd/config/whereabouts/ipam.yml
cmd/config/whereabouts/pod.yml
cmd/config/whereabouts/whereabouts.yml
cmd/ocp.go
whereabouts.go

Similar workload to node-density however applies annotation to the pod to have a secondary interface w/ IP address provide by whereabouts.
The optional `fast_ipam` is a TP feature which is still in development and needs additional RBAC to work (for now).
- Closes #

Adding whereabouts workload

---

cmd/config/cluster-density-v2/deployment-client.yml

Reverts kube-burner/kube-burner-ocp#141

Revert "Decrease readinessProbe period"

---

cmd/config/udn-density-pods/udn-density-pods.yml
udn-density-pods.go

- Optimization
We want to run two cases
- udn and pods are created simultaneously in a namespaces, this is good for stressing the CNI
- wait for udns to come up and then create pods, a more practical approach
to switch between two cases we can simply change the ` --job-pause` time to 1s for case1 or X mins, X depends on how much time it takes to create udns.
Tested locally
```
./bin/amd64/kube-burner-ocp udn-density-pods --iterations=2 --gc=false --churn=false --job-pause 1s
time="2025-01-13 17:10:41" level=info msg="❤️ Checking for Cluster Health" file="cluster_health.go:46"
time="2025-01-13 17:10:41" level=info msg="Cluster is Healthy" file="cluster_health.go:54"
time="2025-01-13 17:10:41" level=info msg="Layer 3 is enabled" file="udn-density-pods.go:54"
<snip>
time="2025-01-13 …
```

Split udn creation and other objects, parameterize job pause

---

cmd/config/udn-density-pods/udn-density-pods.yml

Primary UDNs require the namespaces to be labeled with a known label.

Add the required label to primary UDN namespaces

---

virt-density.go

- Optimization
Increate vmi-ready-threshold timeout from 20 to 25 sec
The CI cluster sometimes hit this timeout.

Increase vmi-ready-threshold timeout

---

cmd/config/udn-density-pods/deployment-client.yml
cmd/config/udn-density-pods/udn-density-pods.yml
udn-density-pods.go

- Optimization
The full workload which includes services and network policies has issues that cause our Prow runs to fail. To prevent missing results due to this bug, it would be beneficial to have a simpler version running. This would mean that metrics can still be tracked, allowing us to detect regressions in a timely manner.

have a udn simple workload as a backup in case the full workload fails

---

cluster-density.go
cmd/config/cluster-density-v2/cluster-density-v2.yml
cmd/config/node-density-cni/node-density-cni.yml
cmd/config/node-density-heavy/node-density-heavy.yml
cmd/config/node-density/node-density.yml
cmd/config/udn-density-pods/udn-density-pods.yml
node-density-cni.go
node-density-heavy.go
node-density.go
udn-density-pods.go

- Optimization
pprofs are almost all the times required to debug a regression in CPU utilization
When our prow runs show this regression we should supplement our logs with these pprofs

add ovn pprof collection to control plane workloads

---

cmd/config/udn-density-pods/udn-density-pods.yml

- Optimization
job name is indexed as udn-density-pods which doesn't let us identify whether the run was l3 or l2

we need seperate udn l2 and l3 job names

---

README.md
cmd/config/virt-capacity-benchmark/check.sh
cmd/config/virt-capacity-benchmark/templates/resize_pvc.yml
cmd/config/virt-capacity-benchmark/templates/secret_ssh_public.yml
cmd/config/virt-capacity-benchmark/templates/vm-snapshot.yml
cmd/config/virt-capacity-benchmark/templates/vm.yml
cmd/config/virt-capacity-benchmark/virt-capacity-benchmark.yml
cmd/ocp.go
common.go
go.sum
test/helpers.bash
test/test-ocp.bats
virt-capacity-benchmark.go

- New feature
Run Virtualization with Storage Capacity Benchmark test

Add virt capacity benchmark test

---

cmd/config/node-density-cni/node-density-cni.yml
cmd/config/node-density-heavy/node-density-heavy.yml
cmd/config/node-density/node-density.yml
node-density-cni.go
node-density-heavy.go
node-density.go
test/test-ocp.bats

- New feature
Enabling churn (default :false) for our node-density tests in kube-burner-ocp
- Closes # https://github.com/kube-burner/kube-burner-ocp/pull/93
Will be verified through CI tests.

Chrun enablement for node-density workloads

---

cmd/config/udn-density-pods/udn-density-pods.yml
udn-density-pods.go

The way that the udn-density-pods workload has currently been implemented, the churn functionality does not ireally work as the UDNs are created in a separate job from the one in which pods/other resoruces are created. This leads to a condition where the `udn-density-l3-pods` job tries to create pods without the UDN, which has been deleted during the churn phase. Thecurrent changes preserve the jobPause functionality by keeping UDN creationin a separate job and enable true churning without pause when requested by user. Churn is also defaulted to false after this change. Current behavior with jobPause is not changed with this patch.
- Refactor
- Bug fix

UDN Churn fix

---

cmd/ocp.go

Currently the go template checks that ES_SERVER is non empty and would throw a rendering error when the variable is not defined. While the intent has always been to make indexing optional, the current implementation does not support that.
We would like to enable cases where users do not care about ES or local indexing and merely want to run load quickly by using something like `kube-burner-ocp node-density` use the stdout to read high level measurements like pod ready latency.
- Bug fix https://github.com/kube-burner/kube-burner-ocp/issues/203

Lower barrier of entry by making indexing truly optional

---

.github/workflows/test-ocp.yml

- Bug fix
- CI
virtctl is downloaded to /tmp so it must be in the PATH

CI - Restore tmp in PATH to allow access to virtctl

---

README.md
common.go
test/test-ocp.bats
virt-capacity-benchmark.go

- Optimization
- CI
Add an option to cleanup all the allocated resources after investigating the test failure

Virt Capacity Benchmark - add option for cleanup only execution

---

cmd/config/cluster-density-v2/deployment-client.yml
cmd/config/rds-core/deployment-client.yml

- Refactor
Remove an extra ignored "env" field to keep manifests clean. Editor automatically removes unnecessary whitespace as well.
No related ticket, just noticed while testing and extracting workloads from kube-burner-ocp

Remove duplicated field "env"

---

cmd/config/virt-density/virt-density.yml
cmd/config/virt-udn-density/virt-udn-density.yml

- Bug fix
For some reason I don't recall now image preload was disabled on these workloads.
- Closes #

Preload vm images

---

README.md
cmd/config/dv-clone/dv-clone.yml
cmd/config/dv-clone/templates/baseImageDataSource.yml
cmd/config/dv-clone/templates/baseImageDataVolume.yml
cmd/config/dv-clone/templates/baseImageDataVolumeSnapshot.yml
cmd/config/dv-clone/templates/cloneImageDataVolume.yml
cmd/ocp.go
dv-clone.go
test/test-ocp.bats

- New feature
Add a new test for creating many DataVolume clones of a single DataVolume.
This test should be used by Storage Vendors to test the limits of their storage as this is a basic flow in creating VirtualMachines from golden images

Add test for DV Cloning

---

cmd/config/udn-bgp/cudn.yml
go.mod
go.sum
pkg/measurements/routeadvertisement-latency_linux.go
udn-bgp.go

routeadvertisement API changed which introduced new fields in networkSelectors. Instead of using ovnk's UDN and RA clientsets, we are now using dynamic client and informers with GVR to watch and fetch UDN and RA.
We will use metrics.yml instead of metrics-aggregated.yml, similar to other UDN workload.
CUDN will be using 40.X.X.X CIDR instead of 10.X.X.X to make BGP route exchange work with AWS cluster.

use RA API v2

---

cmd/config/virt-migration/virt-migration.yml

- Bug fix
Patching the node selector does not change the VM state, there is nothing to wait for
- Closes #263

Virt Migration - skip wait in patch job since VM state does not change

---

README.md
cmd/config/virt-migration/virt-migration.yml
virt-migration.go

- Optimization
- CI
Some clusters are overloaded when handling 20 parallel requests. Allow users to set a different value

Virt Migration - allow users to set QPS for the migration phase

---

cmd/config/cluster-density-v2/deployment-client.yml

The current CDv2 workload use of `readinessProbe` is overwhelming the OpenShift-Ingress `router` in very large-scale clusters (> 250 nodes), due to thousands of routes being probed by client pods every 10s. This causes the router’s CPU usage to spike over 5 cores, and it also impacts pod startup latency, as readiness checks from newly progressing pods compete with ongoing traffic from existing client pods.
AWS handles this scenario well while Azure is struggling at 250-node scale, primarily due to its weaker ingress performance. With 500 node it gets even worse, 9K routes with ~22K client pods at a 10s interval.
In this change,  updating the behavior by replacing the `readinessProbe` with a `startupProbe` that would run only once and mark the container `ready`. This evaluates container …

Updating CDv2 pod ready latency probe

---

cmd/config/metrics-profiles/metrics.yml

Add new metrics for OVS CPU and Memory
- Refactor
- New feature
- Bug fix
- Optimization
- CI
- Related Issue # https://issues.redhat.com/browse/CORENET-6058
- Closes #
This new PR incorporates updates based on review comments from the original [PR ](https://github.com/kube-burner/kube-burner-ocp/pull/280) which was closed due to some difficulty of squashing all commits into one as some commits were merged in from main.
/assign @mohit-sheth
/assign @afcollins
Sorry for having to ask you to review again.  
/cc @jluhrsen
/cc @weliang1

add OVS cpu and memory metrics

---

network-policy.go
olmv1.go
udn-bgp.go

- Bug fix
Some of our workloads have a default value > 0, but we also have a required flag.
We should either :
- remove the default value being >0 OR
- remove the required flag
This PR removes the required flag

Remove the required field to use default

---

README.md
cmd/config/virt-clone/templates/vm.yml
cmd/config/virt-clone/virt-clone.yml
test/test-ocp.bats
virt-clone.go

- New feature
- CI
Virt Clone Test - Allow users to create VMs in iterations instead of all in parallel
- Closes #286

Virt Clone - allow creating VMs in iterations

---

cmd/config/cluster-density-v2/cluster-density-v2.yml
cmd/config/node-density-cni/node-density-cni.yml
cmd/config/node-density-heavy/node-density-heavy.yml
cmd/config/node-density/node-density.yml
cmd/config/udn-density-pods/udn-density-pods.yml

- Bug fix
ovn-controller does not expose a pprof endpoint, so we can remove it from the pprof section to reduce confusion.
```
[root@vm00228 ~]# curl http://localhost:29105/debug/pprof/profile?seconds=5
404 page not found
```

Remove pprof collection from non-existent ovn-controller endpoint

---

README.md
cmd/config/node-scale/namespace.yml
cmd/config/node-scale/node-scale.yml
cmd/config/node-scale/pod.yml
cmd/config/node-scale/rolebinding.yml
cmd/config/node-scale/secret-kubeconfig.yml
cmd/ocp.go
node-scale.go

Leverages [Kubemark](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-scalability/kubemark-guide.md) to create a number of hollow nodes and allow to run experiments on simulated clusters. The primary use case is scalability testing, as simulated clusters can be much bigger than the real ones. The objective is to expose problems with the master components (API server, controller manager or scheduler) that appear only on bigger clusters (e.g. small memory leaks).
```
$ oc get node
NAME              STATUS   ROLES                         AGE   VERSION
vlan604           Ready    control-plane,master,worker   11h   v1.31.11
$ ./kube-burner-ocp node-scale -h
Runs node-scale workload
Usage:
kube-burner-ocp node-scale [flags]
Flags:
--churn …
```

Node scale workload
